---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 300

    - name: "install python for Ansible."
      raw: |
        python -v
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa

  roles:
    - configure-server