---
- name: Get repository for nodejs
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
    sudo apt-get install -y nodejs

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Remove node_modules and dist
  become: true
  shell: /bin/rm -rf /root/project/backend/dist /root/project/backend/node_modules 

- name: Copy backend to server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Start server
  shell:
    cd /home/ubuntu/backend
    npm install
    pm2 start npm -- start
