---
- name: Install the gpg key for nodejs
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs 13.x repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_setup_13.x"
    state: present
    update_cache: yes

- name: Install the nodejs
  apt:
    name: nodejs

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Remove node_modules and dist
  shell: /bin/rm -rf /root/project/backend/dist /root/project/backend/node_modules 

- name: Copy backend to server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Start server
  shell:
    cd /home/ubuntu/backend
    npm install
    pm2 start npm -- start
